AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Spring Boot app on EC2

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  ArtifactBucket:
    Type: String
    Description: S3 bucket path

  ArtifactKey:
    Type: String
    Description: Artifact name in S3

  AppPort:
    Type: Number
    Default: 8080
    Description: Application port

Resources:
  AppEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      DeploymentID: !Ref ArtifactKey   # <-- ключевой триггер пересоздания
    Properties:
      ImageId: ami-07742fc6dc2e6ff6c
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - sg-0e2b0c1ad71a16e31
      KeyName: trade-signals
      Tags:
        - Key: Name
          Value: Deploy demo TEST
        - Key: ArtifactKey
          Value: !Ref ArtifactKey
      IamInstanceProfile: trade-signals-ec2-role
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe
          
          # Create log file
          touch /var/log/trade-signals-app/app.log

          # CloudWatch config
          cat <<EOF >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/trade-signals-app/app.log",
                      "log_group_name": "trade-signals-app-logs",
                      "log_stream_name": "ec2-{instance_id}"
                    }
                  ]
                }
              }
            }
          }
          EOF

          # Start CloudWatch Agent asynchronously
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config -m ec2 \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
            -s || true
          
          # Root access for binding to low ports
          setcap 'cap_net_bind_service=+ep' /usr/lib/jvm/java-17-amazon-corretto/bin/java || true
          
          # Download JAR and start Spring Boot asynchronously on custom port
          aws s3 cp s3://${ArtifactBucket}/${ArtifactKey} /home/ec2-user/app.jar
          chmod +x /home/ec2-user/app.jar
          sudo nohup java -jar /home/ec2-user/app.jar --server.port=${AppPort} > /var/log/trade-signals-app/app.log 2>&1 &

Outputs:
  AppEC2InstanceId:
    Description: EC2 instance ID
    Value: !Ref AppEC2Instance
  PublicIP:
    Description: Public IP
    Value: !GetAtt AppEC2Instance.PublicIp
  URL:
    Description: Full URL
    Value: !Sub "http://${AppEC2Instance.PublicIp}:${AppPort}"
